version: '3.8'
 
services:
  justinsight_service:
    build:
      context: .
      dockerfile: .docker/Dockerfile

    # bind-mount your repo and the shared EBS volume
    volumes:
      - ./:/workspace:cached
      - ./shared:/workspace/shared:cached

    # ensure entrypoint.sh runs (clones & checks out the right branch)
    #entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["bash"]
    stdin_open: true
    tty: true
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - redis
    #entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["celery", "-A", justinsight.celery, "worker", "--loglevel=info"] #the lowercase j is actually so important


