version: '3.8'

services:
  justinsight_service:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    gpus: all

    # bind-mount your repo and the shared EBS volume
    volumes:
      - ./:/workspace:cached
      - ./shared:/workspace/shared:cached

#~/workspace/justinsight

    # ensure entrypoint.sh runs (clones & checks out the right branch)
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["bash"]
    stdin_open: true
    tty: true


    # optional: default branch (can be overridden per-run)
    environment:
       - BRANCH=${BRANCH:-master}

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - /home/${USER}/workspace/justinsight:/workspace:cached
    depends_on:
      - redis
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["celery", "-A", justInsight.celery_app, "worker", "--loglevel=info"] ###justInsight.celery_app ?????

  celery_beat:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - /home/${USER}/workspace/justinsight:/workspace:cached
    depends_on:
      - redis
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["celery", "-A", justInsight.celery_app, "beat", "--loglevel=info"] ###justInsight.celery_app ?????
