services:
  justinsight_service:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - MONGODB_URI=mongodb://myuser:mypassword@mongo:27017/justinsightdb?authSource=admin
    # bind-mount your repo and the shared EBS volume
    volumes:
      - ./:/workspace:cached
      - ./shared:/workspace/shared:cached

    # ensure entrypoint.sh runs (clones & checks out the right branch)
    #entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["bash"]
    stdin_open: true
    tty: true
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - MONGODB_URI=mongodb://myuser:mypassword@mongo:27017/justinsightdb?authSource=admin
    volumes:
      - .:/workspace:cached
      - mongo_data:/data/db 
    depends_on:
      - redis
      - mongo
    #entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["celery", "-A", justinsight.celery, "worker", "--loglevel=info"] #the lowercase j is actually so important

  celery_beat:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - MONGODB_URI=mongodb://myuser:mypassword@mongo:27017/justinsightdb?authSource=admin
    volumes:
      - .:/workspace:cached
    depends_on:
      - redis
    #entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["celery", "-A", justinsight.celery, "beat", "--loglevel=info"] #the lowercase j is actually so important

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
      - .:/workspace:cached

  #will go in the docker-compose.gpu.yml file once we deploy
  celery_gpu_worker:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: ["celery", "-A", justinsight.celery, "worker", "-Q", "gpu", "--loglevel=info"] #the lowercase j is actually so important
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/workspace:cached
      - mongo_data:/data/db 
    depends_on:
      - redis
      - mongo
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  mongo_data: