name: 🗂 Backlog item
description: Propose a new feature, data source, or enhancement
labels:
  - backlog

body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence description
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this valuable?
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - ingestion
        - etl
        - nlp
        - insights
        - ui
      description: Which part of the system?
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
      description: Urgency level
      required: true

  - type: input
    id: estimate
    attributes:
      label: Estimate
      description: Rough time estimate (e.g. 1d, 3d)
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: List out what must be done
      required: true
